title:  "swiftluo"
tagline: "赵田的博客"
description:
author:
  name: "Paul Le"
  twitter: paululele

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Python', file: 'python.html'}
- {name: 'Javascript', file: 'javascript.html'}
- {name: 'Vim', file: 'vim.html'}
- {name: '爬虫', file: 'crawler.html'}
- {name: 'MachineLearning', file: 'ml.html'}
- {name: 'About', file: 'about.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
